"""
Handout Generator Skill
=======================

HARDCODED skill for generating Word document handouts for scripted activities.
This skill CANNOT be bypassed - all activities requiring handouts MUST use this generator.

Supported Activity Types:
- sorting: Myth vs. Fact, True vs. False, Category sorting
- matching: Term matching, Quote matching
- sequencing: Timeline ordering, Process steps
- analysis: Text analysis, Character analysis
- discussion: Discussion prompts with scaffolding
- performance: Scene scripts, Role cards

Requirements:
- All handouts generated as .docx (Word) format
- Student section (no answers) on page 1
- Teacher answer key on page 2 (after page break)
- Consistent formatting and branding

Pipeline: Theater Education
"""

from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


# =============================================================================
# HARDCODED CONSTANTS (CANNOT BE MODIFIED)
# =============================================================================

# Activity types that require handouts
ACTIVITY_TYPES_REQUIRING_HANDOUTS = [
    "sorting",
    "matching",
    "sequencing",
    "analysis",
    "discussion",
    "performance",
    "worksheet",
    "graphic_organizer",
]

# Minimum requirements per handout
MIN_ITEMS_PER_ACTIVITY = 6
MAX_ITEMS_PER_ACTIVITY = 20
REQUIRE_ANSWER_KEY = True
REQUIRE_INSTRUCTIONS = True
REQUIRE_STUDENT_INFO = True


# =============================================================================
# BASE DOCUMENT CREATION
# =============================================================================

def create_base_document(
    title: str,
    subtitle: str,
    unit_day: str,
    include_student_info: bool = True
) -> Document:
    """
    Create base Word document with standard header.

    Args:
        title: Main title of handout
        subtitle: Subtitle (activity type)
        unit_day: Unit and day info (e.g., "Romeo and Juliet Day 1")
        include_student_info: Whether to add name/date fields

    Returns:
        Document object with header populated
    """
    if not DOCX_AVAILABLE:
        raise ImportError("python-docx is required. Install with: pip install python-docx")

    doc = Document()

    # Title
    title_para = doc.add_heading(title, 0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle_para = doc.add_paragraph(subtitle)
    subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Unit/Day info
    doc.add_paragraph(unit_day)
    doc.add_paragraph()

    # Student info fields
    if include_student_info:
        doc.add_paragraph('Name: _________________________________________________')
        doc.add_paragraph('Period: _______     Date: _____________')
        doc.add_paragraph()

    return doc


def add_instructions(doc: Document, instructions: List[str]) -> None:
    """Add numbered instructions section."""
    doc.add_heading('Instructions', level=1)
    for i, instruction in enumerate(instructions, 1):
        doc.add_paragraph(f'{i}. {instruction}')
    doc.add_paragraph()


def add_answer_key_page(doc: Document) -> None:
    """Add page break and answer key header."""
    doc.add_page_break()
    doc.add_heading('Answer Key (Teacher Reference Only)', level=1)
    doc.add_paragraph()


def add_footer(doc: Document, unit_name: str = "Theater Education") -> None:
    """Add footer with pipeline branding."""
    doc.add_paragraph()
    doc.add_paragraph(f'Generated by Theater Education Pipeline - {unit_name}')


# =============================================================================
# SORTING ACTIVITY GENERATOR
# =============================================================================

def generate_sorting_handout(
    title: str,
    unit_day: str,
    items: List[Dict[str, Any]],
    categories: List[str],
    instructions: List[str] = None,
    time_limit: int = 10,
    discussion_questions: List[str] = None,
    output_path: Path = None
) -> Document:
    """
    Generate a sorting activity handout (e.g., Myth vs. Fact).

    HARDCODED: Sorting activities require:
    - Minimum 6 items to sort
    - Exactly 2-4 categories
    - Answer key with explanations

    Args:
        title: Activity title
        unit_day: Unit and day info
        items: List of dicts with 'text', 'category', 'explanation'
        categories: List of category names (e.g., ['MYTH', 'FACT'])
        instructions: Custom instructions (defaults provided)
        time_limit: Minutes for activity
        discussion_questions: Optional discussion prompts
        output_path: Where to save the .docx file

    Returns:
        Document object
    """
    # Validate requirements
    if len(items) < MIN_ITEMS_PER_ACTIVITY:
        raise ValueError(f"HARDCODED: Minimum {MIN_ITEMS_PER_ACTIVITY} items required, got {len(items)}")
    if len(categories) < 2 or len(categories) > 4:
        raise ValueError(f"HARDCODED: 2-4 categories required, got {len(categories)}")

    # Default instructions
    if not instructions:
        instructions = [
            f'Cut out the {len(items)} statement cards below (or use pre-cut cards from envelope)',
            f'Sort each statement into one of the categories: {", ".join(categories)}',
            'Be prepared to explain your reasoning for at least 3 of your choices',
            f'You have {time_limit} minutes to complete this activity'
        ]

    # Create document
    doc = create_base_document(
        title=title,
        subtitle='Sorting Activity',
        unit_day=unit_day
    )

    # Instructions
    add_instructions(doc, instructions)

    # Statement Cards Table
    doc.add_heading('Statement Cards', level=1)

    table = doc.add_table(rows=len(items) + 1, cols=2)
    table.style = 'Table Grid'

    # Header row
    hdr = table.rows[0].cells
    hdr[0].text = '#'
    hdr[1].text = 'Statement'

    # Item rows
    for i, item in enumerate(items):
        row = table.rows[i + 1].cells
        row[0].text = str(i + 1)
        row[1].text = item.get('text', '')

    doc.add_paragraph()

    # Sorting Chart
    doc.add_heading('Sorting Chart', level=1)

    sort_table = doc.add_table(rows=6, cols=len(categories))
    sort_table.style = 'Table Grid'

    # Category headers
    for i, category in enumerate(categories):
        sort_table.rows[0].cells[i].text = category

    doc.add_paragraph()

    # Discussion Questions
    if discussion_questions:
        doc.add_heading('Discussion Questions', level=1)
        doc.add_paragraph('After sorting, discuss these questions with your group:')
        for i, question in enumerate(discussion_questions, 1):
            doc.add_paragraph(f'{i}. {question}')
            doc.add_paragraph()

    # Answer Key (Page 2)
    add_answer_key_page(doc)

    # Group items by category
    for category in categories:
        category_items = [item for item in items if item.get('category') == category]

        doc.add_heading(f'{category} ({len(category_items)} items)', level=2)

        if category_items:
            answer_table = doc.add_table(rows=len(category_items) + 1, cols=3)
            answer_table.style = 'Table Grid'

            # Header
            ans_hdr = answer_table.rows[0].cells
            ans_hdr[0].text = '#'
            ans_hdr[1].text = 'Statement'
            ans_hdr[2].text = 'Explanation'

            # Items
            for i, item in enumerate(category_items):
                row = answer_table.rows[i + 1].cells
                # Find original number
                orig_num = items.index(item) + 1
                row[0].text = str(orig_num)
                row[1].text = item.get('text', '')[:50] + '...' if len(item.get('text', '')) > 50 else item.get('text', '')
                row[2].text = item.get('explanation', '')

        doc.add_paragraph()

    # Footer
    add_footer(doc, unit_day)

    # Save if path provided
    if output_path:
        doc.save(str(output_path))

    return doc


# =============================================================================
# MATCHING ACTIVITY GENERATOR
# =============================================================================

def generate_matching_handout(
    title: str,
    unit_day: str,
    pairs: List[Dict[str, str]],
    left_column_header: str = "Term",
    right_column_header: str = "Definition",
    instructions: List[str] = None,
    time_limit: int = 8,
    output_path: Path = None
) -> Document:
    """
    Generate a matching activity handout.

    HARDCODED: Matching activities require:
    - Minimum 6 pairs
    - Shuffled right column (answers)
    - Answer key with correct matches

    Args:
        title: Activity title
        unit_day: Unit and day info
        pairs: List of dicts with 'left' and 'right' keys
        left_column_header: Header for left column
        right_column_header: Header for right column
        instructions: Custom instructions
        time_limit: Minutes for activity
        output_path: Where to save

    Returns:
        Document object
    """
    import random

    if len(pairs) < MIN_ITEMS_PER_ACTIVITY:
        raise ValueError(f"HARDCODED: Minimum {MIN_ITEMS_PER_ACTIVITY} pairs required")

    # Default instructions
    if not instructions:
        instructions = [
            f'Match each {left_column_header.lower()} on the left with its {right_column_header.lower()} on the right',
            'Write the letter of the correct match in the blank',
            f'You have {time_limit} minutes to complete this activity'
        ]

    doc = create_base_document(
        title=title,
        subtitle='Matching Activity',
        unit_day=unit_day
    )

    add_instructions(doc, instructions)

    # Shuffle right column for student version
    right_items = [p['right'] for p in pairs]
    shuffled_right = right_items.copy()
    random.shuffle(shuffled_right)

    # Matching table
    doc.add_heading('Match the Terms', level=1)

    table = doc.add_table(rows=len(pairs) + 1, cols=3)
    table.style = 'Table Grid'

    # Header
    hdr = table.rows[0].cells
    hdr[0].text = left_column_header
    hdr[1].text = 'Answer'
    hdr[2].text = right_column_header

    # Generate letter labels
    letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

    for i, pair in enumerate(pairs):
        row = table.rows[i + 1].cells
        row[0].text = f'{i + 1}. {pair["left"]}'
        row[1].text = '_____'
        row[2].text = f'{letters[i]}. {shuffled_right[i]}'

    doc.add_paragraph()

    # Answer Key
    add_answer_key_page(doc)

    doc.add_heading('Correct Matches', level=2)

    answer_table = doc.add_table(rows=len(pairs) + 1, cols=3)
    answer_table.style = 'Table Grid'

    ans_hdr = answer_table.rows[0].cells
    ans_hdr[0].text = '#'
    ans_hdr[1].text = left_column_header
    ans_hdr[2].text = f'Answer ({right_column_header})'

    for i, pair in enumerate(pairs):
        row = answer_table.rows[i + 1].cells
        row[0].text = str(i + 1)
        row[1].text = pair['left']
        # Find the letter for this right answer
        answer_letter = letters[shuffled_right.index(pair['right'])]
        row[2].text = f'{answer_letter} - {pair["right"]}'

    add_footer(doc, unit_day)

    if output_path:
        doc.save(str(output_path))

    return doc


# =============================================================================
# SEQUENCING ACTIVITY GENERATOR
# =============================================================================

def generate_sequencing_handout(
    title: str,
    unit_day: str,
    steps: List[Dict[str, str]],
    instructions: List[str] = None,
    time_limit: int = 10,
    output_path: Path = None
) -> Document:
    """
    Generate a sequencing/ordering activity handout.

    Args:
        title: Activity title
        unit_day: Unit and day info
        steps: List of dicts with 'text' and 'order' (correct position)
        instructions: Custom instructions
        time_limit: Minutes for activity
        output_path: Where to save

    Returns:
        Document object
    """
    import random

    if len(steps) < MIN_ITEMS_PER_ACTIVITY:
        raise ValueError(f"HARDCODED: Minimum {MIN_ITEMS_PER_ACTIVITY} steps required")

    if not instructions:
        instructions = [
            'Read all the events/steps below',
            'Number them in the correct order (1 = first, etc.)',
            f'You have {time_limit} minutes to complete this activity'
        ]

    doc = create_base_document(
        title=title,
        subtitle='Sequencing Activity',
        unit_day=unit_day
    )

    add_instructions(doc, instructions)

    # Shuffle steps for student version
    shuffled = steps.copy()
    random.shuffle(shuffled)

    doc.add_heading('Put in Order', level=1)

    table = doc.add_table(rows=len(shuffled) + 1, cols=2)
    table.style = 'Table Grid'

    hdr = table.rows[0].cells
    hdr[0].text = 'Order'
    hdr[1].text = 'Event/Step'

    for i, step in enumerate(shuffled):
        row = table.rows[i + 1].cells
        row[0].text = '_____'
        row[1].text = step['text']

    doc.add_paragraph()

    # Answer Key
    add_answer_key_page(doc)

    doc.add_heading('Correct Order', level=2)

    # Sort by correct order
    sorted_steps = sorted(steps, key=lambda x: x.get('order', 0))

    answer_table = doc.add_table(rows=len(sorted_steps) + 1, cols=2)
    answer_table.style = 'Table Grid'

    ans_hdr = answer_table.rows[0].cells
    ans_hdr[0].text = 'Order'
    ans_hdr[1].text = 'Event/Step'

    for i, step in enumerate(sorted_steps, 1):
        row = answer_table.rows[i].cells
        row[0].text = str(i)
        row[1].text = step['text']

    add_footer(doc, unit_day)

    if output_path:
        doc.save(str(output_path))

    return doc


# =============================================================================
# DISCUSSION ACTIVITY GENERATOR
# =============================================================================

def generate_discussion_handout(
    title: str,
    unit_day: str,
    prompts: List[Dict[str, Any]],
    instructions: List[str] = None,
    time_limit: int = 15,
    output_path: Path = None
) -> Document:
    """
    Generate a discussion activity handout with scaffolding.

    Args:
        title: Activity title
        unit_day: Unit and day info
        prompts: List of dicts with 'question', 'scaffolds' (list), 'sample_response'
        instructions: Custom instructions
        time_limit: Minutes for activity
        output_path: Where to save

    Returns:
        Document object
    """
    if not instructions:
        instructions = [
            'Read each discussion prompt carefully',
            'Use the guiding questions to help form your response',
            'Write your thoughts in the space provided',
            f'You have {time_limit} minutes for this activity'
        ]

    doc = create_base_document(
        title=title,
        subtitle='Discussion Activity',
        unit_day=unit_day
    )

    add_instructions(doc, instructions)

    for i, prompt in enumerate(prompts, 1):
        doc.add_heading(f'Prompt {i}', level=1)
        doc.add_paragraph(prompt.get('question', ''))
        doc.add_paragraph()

        # Scaffolding questions
        if prompt.get('scaffolds'):
            doc.add_paragraph('Guiding Questions:')
            for scaffold in prompt['scaffolds']:
                doc.add_paragraph(f'• {scaffold}')

        doc.add_paragraph()
        doc.add_paragraph('Your Response:')
        doc.add_paragraph('_' * 60)
        doc.add_paragraph('_' * 60)
        doc.add_paragraph('_' * 60)
        doc.add_paragraph()

    # Answer Key with sample responses
    add_answer_key_page(doc)

    for i, prompt in enumerate(prompts, 1):
        doc.add_heading(f'Prompt {i} - Sample Response', level=2)
        doc.add_paragraph(f'Question: {prompt.get("question", "")}')
        doc.add_paragraph()
        doc.add_paragraph(f'Sample Response: {prompt.get("sample_response", "Responses will vary.")}')
        doc.add_paragraph()

    add_footer(doc, unit_day)

    if output_path:
        doc.save(str(output_path))

    return doc


# =============================================================================
# MAIN GENERATION FUNCTION
# =============================================================================

def generate_activity_handout(
    activity_type: str,
    activity_data: Dict[str, Any],
    output_path: Path
) -> Dict[str, Any]:
    """
    Main entry point for generating activity handouts.

    HARDCODED: Routes to appropriate generator based on activity type.

    Args:
        activity_type: One of: sorting, matching, sequencing, discussion
        activity_data: Activity-specific data
        output_path: Where to save the .docx file

    Returns:
        Result dictionary with status and file path
    """
    if not DOCX_AVAILABLE:
        return {
            "status": "error",
            "error": "python-docx not installed"
        }

    generators = {
        "sorting": generate_sorting_handout,
        "matching": generate_matching_handout,
        "sequencing": generate_sequencing_handout,
        "discussion": generate_discussion_handout,
    }

    if activity_type not in generators:
        return {
            "status": "error",
            "error": f"Unknown activity type: {activity_type}. Supported: {list(generators.keys())}"
        }

    try:
        # Extract common fields
        title = activity_data.get("title", "Activity Handout")
        unit_day = activity_data.get("unit_day", "Theater Education")

        # Call appropriate generator
        generator = generators[activity_type]
        doc = generator(
            title=title,
            unit_day=unit_day,
            output_path=output_path,
            **{k: v for k, v in activity_data.items() if k not in ["title", "unit_day"]}
        )

        return {
            "status": "success",
            "file_path": str(output_path),
            "activity_type": activity_type,
            "title": title
        }

    except Exception as e:
        return {
            "status": "error",
            "error": str(e),
            "activity_type": activity_type
        }


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Main function
    "generate_activity_handout",
    # Specific generators
    "generate_sorting_handout",
    "generate_matching_handout",
    "generate_sequencing_handout",
    "generate_discussion_handout",
    # Utilities
    "create_base_document",
    "add_instructions",
    "add_answer_key_page",
    "add_footer",
    # Constants
    "ACTIVITY_TYPES_REQUIRING_HANDOUTS",
    "MIN_ITEMS_PER_ACTIVITY",
    "MAX_ITEMS_PER_ACTIVITY",
]
